language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - pypy
before_install:
  - if [ "${TRAVIS_PYTHON_VERSION::1}" == "3" ]; then export TEST_PKG=unittest2py3k; else export TEST_PKG=unittest2; fi
install:
  - python setup.py install
  - pip install $TEST_PKG
  - pip freeze
script:
  - unit2 discover
matrix:
  allow_failures:
    - python: 3.2 3.3 pypy
