language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - pypy
install:
  - python setup.py install
  - pip freeze
script:
  - python -m unittest discover
matrix:
  allow_failures:
    - python: 3.2
    - python: 3.3
    - python: pypy
